blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),

    url(r'^post/$', PostLV.as_view(), name='post_list'),

    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[0-9]+)/$', PostMAV.as_view(), name='post_month_archive'),

    # /2012/nov/10
    url(r'^(?P<year>\d{4})/(?P<month>[0-9]+)/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    url(r'^search/$', SearchFormView.as_view(), name='search'),

    url(r'^add/$', PostCreateView.as_view(), name='add'),

    url(r'^change/$', PostChangeLV.as_view(), name='change'),

    url(r'^(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='update'),

    url(r'^(?P<pk>\d+)/delete/$', PostDeleteView.as_view(), name='delete'),


]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^admin/', admin.site.urls),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r"^blog/", include('blog.urls', namespace='blog')),
    url(r"^photo/", include('photo.urls', namespace='photo'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from photo.views import *

urlpatterns = [

    url(r"^$", AlbumLV.as_view(), name='index'),

    url(r"^album/$", AlbumLV.as_view(), name='album_list'),

    url(r"^album/(?P<pk>\d+)$", AlbumDV.as_view(), name='album_detail'),

    url(r"^photo/(?P<pk>\d+)$", PhotoDV.as_view(), name='photo_detail'),


    url(r"^album/add/$", AlbumPhotoCV.as_view(), name='album_add'),

    url(r"^album/change/$", AlbumChangeLV.as_view(), name='album_change'),

    url(r"^album/(?P<pk>\d+)/update/$", AlbumPhotoUV.as_view(), name='album_update'),

    url(r"^album/(?P<pk>\d+)/delete/$", AlbumDeleteView.as_view(), name='album_delete'),

    url(r"^photo/add/$", PhotoCreateView.as_view(), name='photo_add'),

    url(r"^photo/change/$", PhotoChangeLV.as_view(), name='photo_change'),

    url(r"^photo/(?P<pk>\d+)/update/$", PhotoUpdateView.as_view(), name='photo_update'),

    url(r"^photo/(?P<pk>\d+)/delete/$", PhotoDeleteView.as_view(), name='photo_delete'),
]

photo/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse
from photo.fields import ThumbnailImageField

from django.contrib.auth.models import User

@python_2_unicode_compatible
class Album(models.Model) :
    name = models.CharField(max_length=50)

    description = models.CharField('One Line Description', max_length=100, blank=True)

    owner = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url (self) :
        return reverse("photo:album_detail", args=(self.id, ))


@python_2_unicode_compatible
class Photo(models.Model) :
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)

    image = ThumbnailImageField(upload_to='photo/%Y/%m')

    description = models.TextField('Photo Description', blank=True)
    update_date = models.DateTimeField('Update date', auto_now_add=True)

    owner = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url (self) :
        return reverse("photo:photo_detail", args=(self.id, ))



@python_2_unicode_compatible
class Publication(models.Model) :
    title = models.CharField(max_length=30)
    albums = models.ManyToManyField(Album)


@python_2_unicode_compatible
class Place(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=80)

    def __str__(self):
        return "%s the place" % self.name

@python_2_unicode_compatible
class Restaurant(models.Model):
    place = models.OneToOneField(Place)

    name = models.CharField(max_length=80, default="DefRestName")

    services_pizza = models.BooleanField(default=False)

    def __str__(self):
        return "%s the restaurant" % self.name

photo/forms.py
from photo.models import Album, Photo
from django.forms.models import inlineformset_factory


PhotoInlineFormSet = inlineformset_factory(Album, Photo,
                                           fields = ['image', 'title', 'description'],
                                           extra = 2)

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin
from photo.forms import PhotoInlineFormSet

# Create your views here.
class AlbumLV(ListView) :
    model = Album


class AlbumDV(DetailView) :
    model = Album


class PhotoDV(DetailView) :
    model = Photo


class PhotoCreateView(LoginRequiredMixin, CreateView) :
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)


class PhotoChangeLV(LoginRequiredMixin, ListView) :
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    success_url = reverse_lazy('photo:index')


class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')


class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner = self.request.user)


class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')


class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photo/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)

        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()

        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']

        for photoform in formset:
            photoform.instance.owner = self.request.user

        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()

            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photo/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)

        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']

        if formset.is_valid() :
            self.object = form.save()
            formset.instance = self.object
            formset.save()

            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

photo/templates/photo/album_change_list.html
{% extends "base.html" %}

{% block title %}Change List{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

        <h1>Album Change = {{ user }}</h1>

        <table class = "charge-list">
            <tr>
                <Th>Name</Th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            {% for item in object_list %}
            <Tr>
                <Td>{{ item.name }}</Td>
                <Td>{{ item.description|linebreaks }}</Td>
                <Td>{{ item.owner }}</Td>
                <Td><a href = "{% url 'photo:album_update' item.id %}">Update</a></Td>
                <Td><a href = "{% url 'photo:album_delete' item.id %}">Delete</a></Td>
            </Tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}

{% block title %}BookForm{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

        <h1>Album Delete</h1>

    <form action = "." method = "post">
    {% csrf_token %}

        <p>Are you sure you want to delete "{{ object }}</p>
        <input type = 'submit' value = "confirm" />
    </form>

    </div>

{% endblock %}

photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}Album Detail{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

    <h2 style = 'display:inline'><a href = "{% url 'photo:album_detail' object.id %}">{{ object.name }}</a></h2>
                    &emsp;<b><I>{{ item.description }}</I></b>

    <hr>

    <div class = "album-detail">
                {% for photo in object.photo_set.all|slice:":5" %}

                    <div class = "album-detail-photo">
                        <a href = "{{ photo.get_absolute_url }}"><img class = "thumbnail" src = "{{ photo.image.thumb_url }}" /></a>
                    <li>{{ photo.title }}</li>
                    <li>{{ photo.update_date|date:"Y-m-d" }}</li>
                    </div>

                {% endfor %}
            </div>

    </div>

{% endblock %}

photo/templates/photo/album_form.html
{% extends "base.html" %}

{% block title %}BookForm{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

        <h1>Album-Photo InlineFormSet</h1>

    {% if form.is_multipart or formset.is_multipart %}
    <form action = "." method = "post" enctype="multipart/form-data">
    {% else %}
    <form action = "." method = "post">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
        <p class = 'errornote'>Wrong! Plase correct the error(s) below</p>
    {% endif %}
    {% if formset.errors %}
        <p class = 'errornote'>Wrong! Plase correct the error(s) below</p>
    {% endif %}



    <h4>Create or Update Album Contents.</h4>

    <fieldset class="aligned">

        <div class = "form-row">
            {{ form.name.label_tag }} {{ form.name }}
        </div>

        <div class = "form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

    </fieldset>

    <h4>Create or Update Photo Contents.</h4>

    {{ formset.management_form }}

    {% for form in fomset %}
        {{ form.id }}

        <fieldset class="aligned">

        <div class = "form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>

            <div class = "form-row">
            {{ form.title.label_tag }} {{ form.title}}
        </div>

        <div class = "form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

    </fieldset>

    {% endfor %}

    <div class = "submit-row">
        <input type = "submit" value = "Submit" />
    </div>

    <script type="text/javascript">
        document.getElementById("id_name").focus ();
    </script>

    </form>

    </div>

{% endblock %}

photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}Album list{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

        {% for item in object_list %}

            <div class = 'clear_float'>

                <h2 style = 'display:inline'><a href = "{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
                &emsp;<b><I>{{ item.description }}</I></b>

            </div>

            <hr>

            <div class = "album-list">
                {% for photo in item.photo_set.all|slice:":5" %}

                    <div class = "album-list-photo">
                        <a href = "{{ photo.get_absolute_url }}"><img class = "thumbnail" src = "{{ photo.image.thumb_url }}" /></a>
                    </div>

                {% endfor %}
            </div>

        {% endfor %}

    </div>

{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends "base.html" %}

{% block title %}Change List{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

        <h1>Photo Change = {{ user }}</h1>

        <table class = "charge-list">
            <tr>
                <Th>Album</Th>
                <Th>Title</Th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            {% for item in object_list %}
            <Tr>
                <Td>{{ item.album }}</Td>
                <Td>{{ item.title }}</Td>
                <Td>{{ item.description|linebreaks }}</Td>
                <Td>{{ item.owner }}</Td>
                <Td><a href = "{% url 'photo:photo_update' item.id %}">Update</a></Td>
                <Td><a href = "{% url 'photo:photo_delete' item.id %}">Delete</a></Td>
            </Tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}BookForm{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

        <h1>Photo Delete</h1>

    <form action = "." method = "post">
    {% csrf_token %}

        <p>Are you sure you want to delete "{{ object }}</p>
        <input type = 'submit' value = "confirm" />
    </form>

    </div>

{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}Photo Detail{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

    <h2>{{ object.title }}</h2>

    <table class = "photo-detail">
        <tr>
            <td>
                <A href = "{{ object.image.url }}"><img style="max-width:100%" src = '{{ object.image.url }}'  /></A>
            </td>
            <td>

                <ul>
                    <li>Photo Description</li>
                    {% if object.description %}
                        <p>{{ object.description|linebreaks }}</p>
                    {% else %}
                        <p>(blank</p>
                    {% endif %}
                    <li>Date Upload</li>
                <p>{{ object.update_date }}</p>
                <li>Alnum name</li>
                <p>
                    <a href = "{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a>
                </p>
                </ul>

            </td>
        </tr>
    </table>

    <h2 style = 'display:inline'><a href = "{% url 'photo:album_detail' object.id %}">{{ object.name }}</a></h2>
                    &emsp;<b><I>{{ item.description }}</I></b>

    <hr>

    <div class = "album-detail">
                {% for photo in object.photo_set.all|slice:":5" %}

                    <div class = "album-detail-photo">
                        <a href = "{{ photo.get_absolute_url }}"><img class = "thumbnail" src = "{{ photo.image.thumb_url }}" /></a>
                    <li>{{ photo.title }}</li>
                    <li>{{ photo.update_date|date:"Y-m-d" }}</li>
                    </div>

                {% endfor %}
            </div>

    </div>

{% endblock %}

photo/templates/photo/photo_form.html
{% extends "base.html" %}

{% block title %}BookForm{% endblock %}

{% load staticfiles %}

{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}

    <div id = 'content'>

        <h1>Photo Create or Update Form</h1>

    {% if form.is_multipart  %}
    <form action = "." method = "post" enctype="multipart/form-data">
    {% else %}
    <form action = "." method = "post">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
        <p class = 'errornote'>Wrong! Plase correct the error(s) below</p>
    {% endif %}



    <fieldset class="aligned">

        <div class = "form-row">
            {{ form.image.label_tag }} {{ form.image }}
        </div>

        <div class = "form-row">
            {{ form.album.label_tag }} {{ form.album }}
            <button type = "button"><a href = "{% url "photo:album_add" %}">Add Album</a></button>
        </div>

        <div class = "form-row">
            {{ form.title.label_tag }} {{ form.title}}
        </div>

        <div class = "form-row">
            {{ form.description.label_tag }} {{ form.description }}
        </div>

    </fieldset>

    <div class = "submit-row">
        <input type = "submit" value = "Submit" />
    </div>

    <script type="text/javascript">
        document.getElementById("id_album").focus ();
    </script>

    </form>

    </div>

{% endblock %}